### ISSUE TITLE
No datum found for datum hash

### ISSUE THREAD

**Issue by jabteles** [cardano-miners/fortuna#18]
Getting error sporadically:

error: Uncaught (in promise) Error: No datum found for datum hash: 5cd10c5dcb34917f94366aa526b46e535f4693d4ac9528ffd50c5d93e46d6d7b
      throw new Error(`No datum found for datum hash: ${datumHash}`);
            ^
    at Kupmios.getDatum (https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:182:13)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async https://deno.land/x/lucid@0.10.1/src/provider/kupmios.ts:238:13
    at async Promise.all (index 0)
    at async Command.actionHandler (file:///C:/Users/xx/Downloads/fortuna-main/fortuna-main/miner/main.ts:121:28)
    at async Command.execute (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1948:7)
    at async Command.parseCommand (https://deno.land/x/cliffy@v1.0.0-rc.3/command/command.ts:1780:14)
    at async file:///C:/Users/xx/Downloads/fortuna-main/fortuna-main/miner/main.ts:417:1

Then the app crashes and the mining stops having to restart the miner

**Comment by BrockCruess** [comment]
Same issue here very often

**Comment by the-vj** [comment]
+1, same issue
